### ISSUE TITLE
JavaScript

### ISSUE THREAD

**Issue by cshaa** [OscarGodson/HTML6#10]
What about inline JS? In the documentation there is no mention of it. I think that `<js:script>` or `<js:inline>` would be good. And what about importing scripts in the html:body? There is a hole in the docs.

**Comment by OscarGodson** [comment]
Good point about the inline script tags. I'd probably do something like:

``` xml
<html:script>
  // JavaScript
  alert('hello world');
</html:script>
```

There's already support for linking to external resources with `<html:link>`, but yeah, there isn't anything for scripts.

What do you mean "importing scripts in the html:body"?

**Comment by cshaa** [comment]
I mean that in HTML5 you can import an external script in the body using `<script src="..."></script>` but if HTML6 used `<html:link>` instead, the script would have to be imported in the head.

Example:

``` html
<!DOCTYPE HTML>
<html>
 <head>
  <meta charset="utf-8" />
  <title>Example</title>
 </head>
 <body>
  <p id="abc">Hola!</p>
  <script src="aslkfdj.js">//This cannot be done in HTML6</script>
 </body>
</head>
```

The problem is that scripts in head can't neither modify nor read elements in body. You can add use `window.onload` event, but it's unnecessarily long. This can be solved by adding something like `loadAtEnd` attribute that will cause `<html:link>`s to be parsed after the body loads.

**Comment by OscarGodson** [comment]
`<html:link>` doesnt have to be in the head. The goal of HTML6 is to consolidate the tags and make the API as small as possible, so if you wanted to do:

``` xml
<html:body>
Hello world
<html:link href="somescript.js">
</html:body>
```

You could. But, the inline scripts you mentioned are a real problem that I totally missed (thanks!). I like the idea of a `<html:script>`. It also allows you to put any sort of script like people do now with `<script type="template">`.
