### ISSUE TITLE
[idea html6] CSS redesign

### ISSUE THREAD

**Issue by philandy** [OscarGodson/HTML6#14]
In the past, I've considered the purpose of CSS heavily. I love what it can do, but what if CSS was incorporated into HTML as if it were a template instead of something alien as the term style implies. The terms template and style(sheet) could become synonyms of sorts.

Bear in mind as you read this, media queries is an issue Oscar and I have been discussing.

Example (external html6 reference): `<html:style src="file.css" />`

Example (html'd css file):

```
<html:style>
    <style:html width="100%">
        <style:body width="100%">
            <style:h color="red" mark="blue" />
        </style>
    </style>
</html>
```

Repo to work on this: https://github.com/philandy/HTMLStyle

**Comment by cshaa** [comment]
That's strange...
How would you write eg. `html div > a! > img:target`?
In my eyes CSS is a great language and it's syntax could be used for even more things than just styling - it can eg. describe document type (instead of DTD or XML Schema). But I agree that CSS3 has lots of mistakes in its documentation so I began to work on "cs" documentation - not Cascading Style Sheets anymore but just Cascading Sheets. My documentation is cca in 10% and it would spend lots of time to complete it but I hope it will be usable some day.
https://github.com/m93a/cs

**Comment by philandy** [comment]
First, I like the idea of cascade anything. So props to that! So for HTML6 we could do a html:cascade or html:cs. I could see that working especially well for DOM code.

On your example, what does `!` mean? The answer to your actual question probably involves nested tags in some way, but some confusion comes up over how to do some things of which might affect the html6 spec itself. Perhaps the internal style node might solve some of it, like `<style:html,div>`, since we know it's only style it's no big deal. Regarding the level selector, the right angle would obviously have to be changed. A distinct option could be backslash, so: `<style:html,div\a!\img:target something="" />`; it's use in escape codes can be exclusively between the quotes.

Then again, this is not to take away anything from CSS. There is no reason why we cannot have `<html:style version="1" src="1.css" /><html:style version="2" src="2.css" /><html:style version="3" src="3.css" />` and `<html:style version="html" src="style.html"><style:tag something="" /></html>` all in the same document.

**Comment by cshaa** [comment]
`<style:html,div\a summin="">` is not a valid SGML. In fact it doesnt matter but how would you integrate this to DOM? It would be hard to manipulate. HTML is a structural language - don't do `<style:foo-bar-qux>` when you can do `<style><foo><bar><qux /></bar></foo></style>`. Do you understand what I'm trying to say?
When you're porting CSS to HTML, make it structural like this:

``` xml
<cs:style>
 <cs:selector>
  <cs:element tag="body" class=".abc">
   <cs:descendant>
    <cs:element>
     <cs:attribute name="data-role" value="content" />
    </cs:element>
   </cs:descendant>
  </cs:element>
 </cs:selector>
 <cs:rules display="block" />
</cs:style>
```

But it's _a bit_ too long to write and means exactly the same as

``` css
body.abc [data-role=content] {
 display:block;
}
```

The exclamation mark in my example is a CSS4 feature, you can find it eg. here: http://css4-selectors.com/selector/css4/subject-of-selector-with-child-combinator/

---

**EDIT:** Or we can use `<html:style for="foobar some selector" rule1="value1" rule2="value2" ... />`, that would be easy to convert back to CSS if it was needed.

**Comment by philandy** [comment]
m93a, CSS does not follow SGML at all, and because it eschews it it can target all of several types of tags at the same time.

Your example is not SGML at all, but mine approaches it and arguably could work.

**Comment by philandy** [comment]
"`<html:style for="foobar some selector" rule1="value1" rule2="value2" ... />`"
You're introducing for="tag". This would be confusing; just use CSS.

**Comment by cshaa** [comment]
You really wanna use tags named `style:html,div\a!\img:target`?

**Comment by OscarGodson** [comment]
haha, that looks kinda looks like regex's ugly cousin ;)

**Comment by philandy** [comment]
@m93a, no I don't. You asked me to build a tag to traverse the DOM, using CSS. CSS already has a way to do that, which is impossible to read without a comment or Google on hand, for the new viewer.

Tell me how you would get CSS to look through the DOM tree?

The obvious method is XSL: `/html/body/div` Sadly, HTML already uses slash to close things. The alternative is the backslash which has been used in DOS systems in the past: `\html\body\div`. HTML does not use the backslash and you would only have potential problems with JavaScript and escaped characters. Luckily, CSS needs no escape characters so contextually there is no problem at all.

I suggested the comma, because I dislike using spaces. Spaces in HTML means moving to a new part of that specific tag, not to a different tag reference. Comma would be a more obvious choice. Why are multiple tag references in CSS important? `div p {whatever:whatever;}` comes to mind. The same example in HTML6 styles would be `<div,p whatever="whatever">`

**Comment by cshaa** [comment]
There's no need of creating a new syntax. There is no problem with CSS. Your solution will only confuse programmers. I think that we should make a reform in styling but not this way.

**Comment by philandy** [comment]
@m93a, this is new territory. Code has never been designed around the concept of confusion, as code is confusing no matter what you do until the point where it actually becomes a natural language, which hasn't happened yet.

For a template, starting users will do only 1 or 2 things with the styles so they get it - an element and an attribute.
`<body width="100%">`

After that they may add another attribute or start nesting...
`<html><body something="something"></html>`

They then find out they didn't need to nest...
`<html\body something="something">` or we can do `<html/body something="something">` if we can ensure it doesn't start the element, right? You tell me.

**Comment by cshaa** [comment]
OK, let's start experimenting. Would you write a documentation, please? As a new repository. I'll read it and try to help.

**Comment by philandy** [comment]
https://github.com/philandy/HTMLStyle

**Comment by OscarGodson** [comment]
I'm going to close this since CSS is technically out of the scope of HTML6. You can continue the discussion there tho :) thanks!
