### ISSUE TITLE
No need for master branch

### ISSUE THREAD

**Issue by zaz** [OscarGodson/HTML6#19]
The `publish.sh` script and `master` branch are redundant. Why not set `gh-pages` as the default branch and get rid of `master`?

**Comment by OscarGodson** [comment]
Good point. Made gh-pages the default and deleted master.

**Comment by zaz** [comment]
Oh no, now the butterfly's disappeared D: That was the best part!

Haha, I'm just kidding. I don't agree with the proposal (you might have heard me mention that before :P), but I nonetheless find your ideas interesting.

But seriously; the butterfly was nice. We should fix this: @29d61cb.

Good job! The butterfly is back.
