### ISSUE TITLE
Renaming the language and namespace

### ISSUE THREAD

**Issue by cshaa** [OscarGodson/HTML6#21]
As said in #17, renaming this repo to NML (namespace markup language) or NHTML would (namespace hypertext markup language) would be more accurate. To make the web-writing faster, the `html` namespace could be renamed to `n` - that's short enough :)  
And the `html:html` would be `n:root` (or `n:html` to keep the tradition?)

**Comment by philandy** [comment]
That would require a major rewrite of everything (not saying that's wrong). I would consider this transitional and leaving it as html is not wrong.

Further, due to being explicit for the greater good, `n:` is wrong. At minimum it would be `name:`.

**Comment by cshaa** [comment]
Why is `n:` wrong? Nobody uses this namespace as far I know. And it would be faster to write.

**Comment by OscarGodson** [comment]
@m93a It's not explicit. HTML wasn't meant to type super fast (or else all tags would just be 1-3 characters) it's meant to be read. As I've stated in other tickets, the point of my proposal is to not make a markup language optimized for typing, but for reading (semantics). For one, you should be writing very little HTML when building any app or web site aside from the initial page code up, which even then is only a few hours.

As for the name change, HTML6 is mostly just for marketing. It is different than HTML and should have a different name, _however_, if I change it 90% of the traffic to the repo would be lost. "HTML6" brings this site up as #1 on Google and Bing and Google Analytics shows people looking up "html6" is the number 1 driver to the site.

**Comment by cshaa** [comment]
Or the language itself would be _nml_ and _html_ (version 6) would be one of its APIs.
