### ISSUE TITLE
Merging HTML6 with SVG and MathML

### ISSUE THREAD

**Issue by cshaa** [OscarGodson/HTML6#27]
It would be nice to make a HTML6-style documentation for SVG, GraphML and MathML.
Eg. MathML is useful but not very practical. We could add `math` prefix to this spec and remove those `m`s from the begining of the tag names and `math` from the attribute names.

**Comment by OscarGodson** [comment]
I'm not sure SVG and MathML belong in the HTML6 repo :) they're their own specs. You could create your own repo for those if you want.
