### ISSUE TITLE
Tags should be closed in html6

### ISSUE THREAD

**Issue by exabrial** [OscarGodson/HTML6#34]
A tag like 

```
<html:link src="js/main.js" title="Main Script" type="text/javascript">
```

Does not communicate developer intent. Is the next tag a child of `<html:link>` or a peer?

Simply closing the tag with one additional, JUST ONE, just one extra, keystroke simplifies parsing of the document and sends an extremely clear message. Simplifying the document structure should also lead to improved render times, as browsing engines don't have to look ahead and make all sorts of guesses.

```
<html:link src="js/main.js" title="Main Script" type="text/javascript" />
```

**Comment by cshaa** [comment]
Yeah, totally agree. But it's a duplicate of issue #8. Close this?

**Comment by exabrial** [comment]
Yep definitely a duplicate. Thanks!
