### ISSUE TITLE
No CSS pseudo class selector support

### ISSUE THREAD

**Issue by jamescostian** [OscarGodson/HTML6#37]
It's impossible to use CSS [pseudo class selectors](http://css-tricks.com/pseudo-class-selectors/). That's excruciatingly limiting.

**Comment by cshaa** [comment]
Not true. CSS would be used in the same manor as it's now in XML.
See this website for more info: [MDN - @namespace](https://developer.mozilla.org/en-US/docs/Web/CSS/@namespace)

@OscarGodson Close?

**Comment by jamescostian** [comment]
Ew that's disgusting. But hey, to each his/her own.
