### ISSUE TITLE
Lol, worse syntax I've ever seen.

### ISSUE THREAD

**Issue by ghost** [OscarGodson/HTML6#45]
"<html:html>"

LMAO Really? This html6 syntax has got to be a joke and you should pull down your site. Don't try to re-invent the wheel.

**Comment by OscarGodson** [comment]
I suggest reading the very first paragraph on the site:

> UPDATE: I copy pasted this years ago, from a blog I don't write at anymore. I first published this nearly three years ago. The site is getting a ton of traffic out of nowhere. I haven't updated this aside from minor typos since then. Seriously, it was just some random thing I did for fun one day. It's in no way a real spec and should not be taken seriously.

P.S. it uses XML syntax specifically to _not_ reinvent the wheel. As it said above, this is pretty old, but XML namespaces are far older. XML Namespaces 1.0 came out in 2009 and was in draft for years before that.

**Comment by ghost** [comment]
Lol no one cares. That is not even true XML syntax.... You don't use fucking colons inside the carrots...

**Comment by OscarGodson** [comment]
http://www.w3schools.com/xml/xml_namespaces.asp

**Comment by OscarGodson** [comment]
Locking the topic because of trolls
