### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by CosmicWebServices** [OscarGodson/HTML6#48]
How about no more css (or at least less of it)!

Like this:

```
<color type="#0000">
```

something like that

**Comment by cshaa** [comment]
That's what HTML2 was like :D
This approach becomes absolutely useless when you're dealing with more elements that have to look the same. Furthermore, there's a general tendency to separate content, style and scripts into another files for much better scalability of the apps created. What's wrong with CSS?

**Comment by CosmicWebServices** [comment]
Ok
