### ISSUE TITLE
[Question] HTML6 vs. x-tag-elements?

### ISSUE THREAD

**Issue by leoj3n** [OscarGodson/HTML6#6]
What's the relatedness between this and [x-tag-elements by Mozilla](https://github.com/mozilla/x-tag-elements)?

**Comment by OscarGodson** [comment]
Not quite sure what that is. No demo or docs as far as I can see.

**Comment by leoj3n** [comment]
See [x-tag repo](https://github.com/mozilla/x-tag) and http://x-tags.org/

**Comment by leoj3n** [comment]
[Web components](https://dvcs.w3.org/hg/webcomponents/raw-file/tip/explainer/index.html#introduction) might be useful.

**Comment by OscarGodson** [comment]
So, x-tag looks like just a bunch of more tags which is great, but still restrictive and not what my concept is all about. Mine is about less structure and more freedom for the devs.
