### ISSUE TITLE
New "semantic" tags

### ISSUE THREAD

**Issue by maxw3st** [OscarGodson/HTML6#7]
I'm leaving this here at your request. It really relates more to HTML5 and some of the new semantic tags. In response to your comment from the bottom of the type="someSortOfMedia" issue. I got off track onto an ARIA related thought.

Header, nav, section, aside, and article aren't random empty tags. And, they do add a lot of space around content I put in them, that has nothing to do with any padding, line-height, or margins I've marked up. I've messed with them several times. The browsers are adding box padding, or borders, or margins, or line-height, or something, that's almost impossible to override. It messes up layout. So, like I said previouisly, I don't use the tags unless I know I have lots of room to give them. Like header for instance. That usually works ok because it'll create a header that's about the right height. 

On a current site, I had to give up on using the nav tag for my main navigation links because it was generating just too much vertical size for the element. I'm using a div instead, and it works fine now.

**Comment by OscarGodson** [comment]
They shouldn't be: http://jsbin.com/exohar/1/

Notice how they're all exactly the same height, same margins, padding, etc.

**Comment by maxw3st** [comment]
Oscar, that looks great in the jsbin. But it hasn't been my experience when marking up html docs. I understand what you're saying and agree completely, it just isn't my direct experience. I have to go with what I see on the monitors in front of me in multiple browsers. 

Personally, I have no problem using project specific semantic classes in div tags. It matches my CSS to the document involved and its content. Next time I have an 'aside' in a page, I'll try using the tag again. If I want to have a nav bar that occupies 80 pixels of screen height and it's own un–shared vertical space, I'll use the nav tags. But that look is tired and I'm trying something else on my latest.

**Comment by OscarGodson** [comment]
That's just a raw HTML doc (view the source). Can you give me a gist to look at? Browsers shouldn't be adding anything to headers and stuff. They're basically just divs with meaning.

**Comment by cshaa** [comment]
If HTML5 did this, HTML6 should not. All the tags should be equal.

**Comment by cshaa** [comment]
Close this?
